# Generated by Django 4.1.7 on 2023-08-31 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='coordinate',
            name='lng',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='destination_lat',
            field=models.FloatField(default=34.801698, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='destination_lng',
            field=models.FloatField(default=48.704824, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='origin_lat',
            field=models.FloatField(default=35.699756, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='origin_lng',
            field=models.FloatField(default=51.338076, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
